PRE_TRAINED_WEIGHTS_FOR_HEAT_MAP = './model0122.pth.tar'

LIST_NN_ARCHITECTURE = ['feature_extractor', 'DENSE-NET-121', 'DENSE-NET-169', 'DENSE-NET-201']
NN_ARCHITECTURE = LIST_NN_ARCHITECTURE[0]
NN_IS_PRE_TRAINED = True

TRANS_RESIZE = 256
TRANS_CROP = 224